### ISSUE TITLE
Doesn't work on Ideapad Slim 5 

### ISSUE THREAD

**Issue by 103sbavert** [shaansubbaiah/powercontrol#4]
This is an awesome Idea (get it?) but it doesn't work on my Ideapad Slim 5. I much prefer this over TLP which doesnt even let you enable quick/rapid charge. I don't know what logs to provide but calling either `-r` or `-c` says
>Something went wrong, exiting :(

**Comment by shaansubbaiah** [comment]
Do you have acpi_call installed? Are you running the Ryzen 4700u variant? The newer 5000 series has slightly different calls.

**Comment by 103sbavert** [comment]
It's an Intel running Ideapad 5-15ITL05
below are the specs:
*Processor*
1x 11th Generation Intel® Core™ i5-1135G7 Processor(Core™ i5-1135G7)
*Memory*
1x 16GB DDR4 3200
*Hard Drive*
1x 512GB PCIe QLC
*Wireless Network*
1x Intel® Wi-Fi 6 AX201 2x2 AX; Bluetooth® 5.0 or above
*Ports*
1x 1 Type C (USB 3.2 Gen 2 + DP 1.2 + PD 3.0); 2 USB 3.1 (Gen1); Combo of 3.5mm Stereo Headphone Output; DC-in Jack (Round); HDMI 1.4b; SD Card reader
*Camera*
1x 720P HD with Dual Array Microphone
*Graphics*
1x Intel® Iris® Xe Graphics

**Comment by shaansubbaiah** [comment]
That must be the newer/different model in the Intel variant. I think the Arch Wiki has a topic for that laptop somewhere, you'll have to change the ACPI call statements for the newer model if it exists.

As an alternative, you can try [ideapad-cm](https://aur.archlinux.org/packages/ideapad-cm/) if you're using an Arch-Linux based distribution.

**Comment by 103sbavert** [comment]
Thank you for your response. Unfortunately, I cannot find any page on ArchWiki for my laptop. There's a table entry regarding it saying that the fingerprint sensor (of an older model) doesn't work but that's it. 

About the alternative you posted, I looked at the code and it only helps with conservation mode and not with quick/fast/rapid charging. I already know how to enable/disable conservation mode.
